#!/bin/sh

if [ -z "$NODE_PATH" ];
then
  task="/var/runtime:/var/task"
  node_dir="/opt/nodejs/bin/node"
  index=/opt/aws/index.js
  export NODE_PATH="$task:$node_dir"
fi

if [ -n "$AWS_LAMBDA_FUNCTION_MEMORY_SIZE" ];
then
  new_space=$(expr $AWS_LAMBDA_FUNCTION_MEMORY_SIZE / 10)
  semi_space=$(expr $new_space / 2)
  old_space=$(expr $AWS_LAMBDA_FUNCTION_MEMORY_SIZE - $new_space)
  MEMORY_ARGS=(
    "--max-semi-space-size=$semi_space"
    "--max-old-space-size=$old_space"
  )
fi

# Set the node version
export NODE_VERSION=$(exec $node_dir --version)

exec env \
  $node_dir \
  --expose-gc \
  --max-http-header-size 81920 \
  "${MEMORY_ARGS[@]}" \
  $index
